---
title: "DGE Projekt"
output: html_document
date: "2026-01-08"
---

```{r}
#Load Packages
library(DESeq2)
library(dplyr)
library(GEOquery)
library(tidyverse)
library(ggrepel)
library(apeglm)
library(data.table)
library(ggplot2) 
library(patchwork)  # for combining plots
library(org.Hs.eg.db)
library(AnnotationDbi)
```

## Download, filter and prepare data

### Download using wget

```{bash}
#Metadate
#wget --directory-prefix=data https://ftp.ncbi.nlm.nih.gov/geo/series/GSE260nnn/GSE260603/matrix/GSE260603_series_matrix.txt.gz

#Rawcounts for analyzis
#wget --directory-prefix=data https://ftp.ncbi.nlm.nih.gov/geo/series/GSE260nnn/GSE260603/suppl/GSE260603%5Fraw%5Fcounts.tsv.gz

#Normalize data
#wget --directory-prefix=data https://ftp.ncbi.nlm.nih.gov/geo/series/GSE260nnn/GSE260603/suppl/GSE260603%5Fnormalized%5Fdata.tsv.gz
```

```{bash}
ls data
```

# Read metadate and filter

```{r}
#Read metadata and inspect
gse <- getGEO(filename="data/GSE260603_series_matrix.txt.gz", GSEMatrix=TRUE)
metadata <- pData(gse)
colnames(metadata)

```

```{r}
#Rename and filter
old_names <- c("age:ch1", "Sex:ch1", "bmi:ch1", "characteristics_ch1.4")
new_names <- c("age", "gender", "bmi", "affected")

colnames(metadata)[match(old_names, colnames(metadata))] <- new_names


```

```{r}
#Deal with brake row. For 'GSM8120701' there is some EROR in data. 
if (metadata['GSM8120701', 13] == 	"status: affected"){
  metadata['GSM8120701', 14:20] <- metadata['GSM8120701', 13:19] 
  metadata['GSM8120701', 13]<-NaN
  print(metadata[c('GSM8120701', 'GSM8120825', 'GSM8120638'), 13:20])
}
```

```{r}
#Chose columns
metadata_filt<-metadata[c('title', 'age', 'gender', 'bmi','affected')]


#New rownems
metadata_filt$title <- gsub(".*(sample_[0-9]+).*", "\\1", metadata_filt$title)

#Drop rows with "status: affected; for replication analysis"
metadata_filt<-subset(metadata_filt, affected!="status: affected; for replication analysis")

#Chcnage afected
metadata_filt$affected <- gsub("status: (.*)", "\\1", metadata_filt$affected)

#Set new rownames
rownames(metadata_filt) <- metadata_filt$title
metadata_filt<-subset(metadata_filt, select=-(title))


class(metadata_filt$bmi)
# Convert BMI and age to numeric if needed
metadata_filt$bmi <- as.numeric(metadata_filt$bmi)
metadata_filt$age <- as.numeric(as.character(metadata_filt$age))

metadata_filt
```

```{r}
#Visual check of metadata
bmi <- ggplot(metadata_filt, aes(x=bmi)) + 
  geom_histogram()
age <- ggplot(metadata_filt, aes(x=age)) + 
  geom_histogram()
(bmi|age)
```

```{r}
#Count male and female
summary_table <- metadata_filt %>%
  group_by(affected, gender) %>%
  summarise(n = n(), .groups = "drop")

summary_table

ggplot(summary_table, aes(x = affected, y = n, fill = gender)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(
    title = "Count of male and female in groups",
    x = "Group",
    y = "Liczba próbek",
    fill = "Gender"
  )

```

# Read and filter count matrix

```{r}
#Get count matrix
counts <- data.table::fread("data/GSE260603_raw_counts.tsv.gz")
```

```{r}
#COnvert to array 
gene_ids <- counts[[1]]
count_matrix_raw <- as.matrix(counts[, -1])
rownames(count_matrix_raw) <- gene_ids
class(count_matrix_raw)
```

```{r}
#Filter out gene on chromosome Y
#Map Gene to chromosome
chr_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = rownames(count_matrix_raw),
  keytype = "ENSEMBL",
  columns = "CHR"
)

# Filter out Y
genes_Y <- chr_map$ENSEMBL[chr_map$CHR == "Y"]
genes_Y<-unique(genes_Y)

# FIlter out genes form count matrix
count_matrix <- count_matrix_raw[
  !rownames(count_matrix_raw) %in% genes_Y,
]

```

## Read and filter Normalized data

```{r}
data_normalized <- read_tsv(file = "data/GSE260603_normalized_data.tsv")
data_normalized 
```

```{r}
# Transpose
df_t <- t(data_normalized)

# Convert to data frame
df_t <- as.data.frame(df_t)
colnames(df_t) <- as.character(unlist(df_t[1,]))
df_t<-df_t[-1,]
df_t
```

```{r}
expr <- data_normalized %>%
  as.data.frame()

rownames(expr) <- expr$Geneid
expr$Geneid <- NULL

expr <- as.matrix(expr)
storage.mode(expr) <- "numeric"
pca <- prcomp(t(expr), center = TRUE, scale. = TRUE)
```

```{r}
# data frame
pca_df <- as.data.frame(pca$x) %>%
  mutate(sample = rownames(.))
pca_df
```

## Inspect data

```{r}

# Combine PCA coordinates with metadata
pca_metadata_df <- cbind(pca_df, metadata_filt)

# pca gender
p1 <- ggplot(pca_metadata_df, aes(x = PC1, y = PC2, color = gender)) +
  geom_point(size = 3, alpha = 0.8) +
  labs(title = "Gender", color = "Gender") +
  theme_minimal(base_size = 12)

#pca affect
p2 <- ggplot(pca_metadata_df, aes(x = PC1, y = PC2, color = affected)) +
  geom_point(size = 3, alpha = 0.8) +
  labs(title = "Affected", color = "Affected") +
  theme_minimal(base_size = 12)

#pca bmi)
p3 <- ggplot(pca_metadata_df, aes(x = PC1, y = PC2, color = bmi)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_gradient(low = "lightblue", high = "darkblue") +
  labs(title = "BMI", color = "BMI") +
  theme_minimal(base_size = 12)

# pca age
p4 <- ggplot(pca_metadata_df, aes(x = PC1, y = PC2, color = age)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_gradient(low = "lightgreen", high = "darkgreen") +
  labs(title = "Age", color = "Age") +
  theme_minimal(base_size = 12)

# Combine 4 plots into 2x2 grid
(p1 | p2) / (p3 | p4)

```

### Checkpoint

```{r}

#Save raw data
#save(metadata, counts, file = "RData/input_raw.RData")

#SAVE DATA load for dds 
#save(metadata_filt, count_matrix, file = "RData/input_for_DGE_all.RData")
#load("RData/input_for_DGE_all.RData")
```

## Use DESeq2

```{r}
#Perform DGE
dds <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = metadata_filt,
  design = ~ affected + gender
)

dds <- dds[rowSums(counts(dds)) > 10, ]
dds <- DESeq(dds)
```

```{r}
#Checkpoint
#save(dds, file="RData/dds_all.Rdata")
#load("RData/dds_all.Rdata")
```

```{r}
#Set pval and logfc
pval=0.01
logfc=2
```

```{r}
#Normalize
norm_counts <- DESeq2::counts(dds, normalized = T)

# Get result
res <- results(dds)

#Convert to data frame
dge_res_df <- as.data.frame(res)

#Drop row with Na in padj
dge_res_df <-drop_na(dge_res_df)

# Add a column to the data frame to specify if they are UP- or DOWN- regulated (log2fc respectively positive or negative)
dge_res_df$diffexpressed <- "NO"

# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP"
dge_res_df$diffexpressed[dge_res_df$log2FoldChange > logfc & dge_res_df$pval < pval] <- "UP"

# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
dge_res_df$diffexpressed[dge_res_df$log2FoldChange < -logfc & dge_res_df$pval < pval] <- "DOWN"# Explore a bit


#Filter down genes
overexpressed_genes <- subset(dge_res_df, diffexpressed!="NO")  

dge_res_df
```

```{r}
plotDispEsts(dds)
```

## Volcano Plot

```{r}
ggplot(data = dge_res_df, aes(x = log2FoldChange, y = -log10(padj), col = diffexpressed)) +
  geom_vline(xintercept = c(-logfc,logfc), col = "gray", linetype = 'dashed') +
  geom_hline(yintercept = -log10(pval), col = "gray", linetype = 'dashed') + 
  geom_point(size = 2) + 
  scale_color_manual(values = c("#00AFBB", "grey", "#bb0c00"), 
                     labels = c("Downregulated", "Not significant", "Upregulated")) + 
  coord_cartesian(ylim = c(0, 200), xlim = c(-10, 10)) + 
  labs(color = 'Genes', #legend_title, 
       x = expression("log"[2]*"FC"), 
       y = expression("-log"[10]*"p-adj")) + 
  scale_x_continuous(breaks = seq(-10, 10, 2)) +
  ggtitle('DGE bet') 
 
```

# PCA

```{r}
to_PCA <- norm_counts %>% t() # transpose a table (rows become columns)

#Run PCA
pca <- prcomp(to_PCA) #run PCA (the result is a list)

#Transform to dataframe
#Tu się coś wykrzacza ale wystarzy pujśc dalej i działa xd
pca_plot <- as.data.frame(pca$x) 
pca_plot
```

```{r}
# Combine PCA coordinates with metadata
pca_metadata_df <- cbind(pca_plot, metadata_filt)

# pca gender
p1 <- ggplot(pca_metadata_df, aes(x = PC1, y = PC2, color = gender)) +
  geom_point(size = 3, alpha = 0.8) +
  labs(title = "Gender", color = "Gender") +
  theme_minimal(base_size = 12)

#pca affect
p2 <- ggplot(pca_metadata_df, aes(x = PC1, y = PC2, color = affected)) +
  geom_point(size = 3, alpha = 0.8) +
  labs(title = "Affected", color = "Affected") +
  theme_minimal(base_size = 12)

#pca bmi)
p3 <- ggplot(pca_metadata_df, aes(x = PC1, y = PC2, color = bmi)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_gradient(low = "lightblue", high = "darkblue") +
  labs(title = "BMI", color = "BMI") +
  theme_minimal(base_size = 12)

# pca age
p4 <- ggplot(pca_metadata_df, aes(x = PC1, y = PC2, color = age)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_gradient(low = "lightgreen", high = "darkgreen") +
  labs(title = "Age", color = "Age") +
  theme_minimal(base_size = 12)

# Combine 4 plots into 2x2 grid
(p1 | p2) / (p3 | p4)
```

# Gene function

```{r}
library(biomaRt)
over_genes_name <- rownames(overexpressed_genes)
```

```{r}

# connect to Ensembl
ensembl <- useMart(
  biomart = "ensembl",
  dataset = "hsapiens_gene_ensembl"
)

# get annotations
annot_over_genes <- getBM(
  attributes = c(
    "ensembl_gene_id",
    "hgnc_symbol",
    "description",
    "gene_biotype"
  ),
  filters = "ensembl_gene_id",
  values = over_genes_name,
  mart = ensembl
)

annot_over_genes
```
```{r}
write_csv(annot_over_genes, file="data/overexpressed_genes.csv")
```

