---
title: "HTS DGE depression report"
author:
  - name: Maya Śliwa
  - name: Igor Mokrytskyi
  - name: Jan Rysiak
date: 2026-10-07
date-format: "d MMM yyyy"
affiliations:
  - id: JU
    name: Jagiellonian University
format: 
  html:
    df-print: kable
    tidy: false
    embed-resources: false
    self-contained: false
    theme: lumen
    toc: true
    toc-location: left
    toc-depth: 6
    toc-expand: 6
    code-tools:
      source: true
      toggle: true
    code-fold: false
    code-summary: "Show the code"
    code-overflow: wrap
    page-layout: full
execute:
  cache: true
  eval: true
editor: visual
---

```{r}
# Load packages
library(tidyverse)
library(ggplot2)
library(DESeq2)
library(GGally)
library(patchwork)
library(knitr)

```

```{r}
# Load precomputed objects
dds <- readRDS("RData/dds.rds")
metadata_filt <- readRDS("RData/metadata_filt.rds")
norm_counts <- readRDS("RData/norm_counts.rds")
pca_df_before <- readRDS("RData/pca_df_before.rds")
pca_plot <- readRDS("RData/pca_plot.rds")
dge_res_df <- read.csv("data/dge_res_df.csv", row.names = 1)
clusters <- read.table("sumo/LAML/k2/clusters.tsv", header=TRUE)

```

# Inspect data
```{r}
#| fig.path: "figures/male_female_"
#| fig.width: 6
#| fig.height: 5
#| dpi: 150
#Count male and female
summary_table <- metadata_filt %>%
  group_by(affected, gender) %>%
  summarise(n = n(), .groups = "drop")


# Plot 
ggplot(summary_table, aes(x = affected, y = n, fill = gender)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(
    title = "Count of male and female in groups",
    x = "Group",
    y = "Liczba próbek",
    fill = "Gender"
  )

```
```{r}
#| fig.path: "figures/pca_"
#| fig.width: 6
#| fig.height: 5
#| dpi: 150

p1 <- ggplot(pca_df_before, aes(x=PC1, y=PC2, color=metadata_filt$gender)) +
  geom_point(size=3, alpha=0.8) +
  labs(title="PCA by Gender", color="Gender") +
  theme_minimal()

p2 <- ggplot(pca_plot, aes(x=PC1, y=PC2, color=metadata_filt$affected)) +
  geom_point(size=3, alpha=0.8) +
  labs(title="PCA by Affected", color="Affected") +
  theme_minimal()

p3 <- ggplot(pca_plot, aes(x=PC1, y=PC2, color=metadata_filt$bmi)) +
  geom_point(size=3, alpha=0.8) +
  scale_color_gradient(low="lightblue", high="darkblue") +
  labs(title="PCA by BMI", color="BMI") +
  theme_minimal()

p4 <- ggplot(pca_plot, aes(x=PC1, y=PC2, color=metadata_filt$age)) +
  geom_point(size=3, alpha=0.8) +
  scale_color_gradient(low="lightgreen", high="darkgreen") +
  labs(title="PCA by Age", color="Age") +
  theme_minimal()

(p1 | p2) / (p3 | p4)

```




# Volcano plot
```{r}
#| fig.path: "figures/volcano_"
#| fig.width: 6
#| fig.height: 5
#| dpi: 150

logfc <- 1
pval <- 0.01

ggplot(dge_res_df, aes(x=log2FoldChange, y=-log10(padj), col=diffexpressed)) +
  geom_vline(xintercept=c(-logfc, logfc), linetype="dashed", col="gray") +
  geom_hline(yintercept=-log10(pval), linetype="dashed", col="gray") +
  geom_point(size=2) +
  scale_color_manual(values=c("#00AFBB","grey","#bb0c00")) +
  labs(x="log2FC", y="-log10(adj p-value)", color="Gene") +
  theme_minimal()

```
```{r}
#| fig.path: "figures/pca_"
#| fig.width: 6
#| fig.height: 5
#| dpi: 150

p1 <- ggplot(pca_plot, aes(x=PC1, y=PC2, color=metadata_filt$gender)) +
  geom_point(size=3, alpha=0.8) +
  labs(title="PCA by Gender", color="Gender") +
  theme_minimal()

p2 <- ggplot(pca_plot, aes(x=PC1, y=PC2, color=metadata_filt$affected)) +
  geom_point(size=3, alpha=0.8) +
  labs(title="PCA by Affected", color="Affected") +
  theme_minimal()

p3 <- ggplot(pca_plot, aes(x=PC1, y=PC2, color=metadata_filt$bmi)) +
  geom_point(size=3, alpha=0.8) +
  scale_color_gradient(low="lightblue", high="darkblue") +
  labs(title="PCA by BMI", color="BMI") +
  theme_minimal()

p4 <- ggplot(pca_plot, aes(x=PC1, y=PC2, color=metadata_filt$age)) +
  geom_point(size=3, alpha=0.8) +
  scale_color_gradient(low="lightgreen", high="darkgreen") +
  labs(title="PCA by Age", color="Age") +
  theme_minimal()

(p1 | p2) / (p3 | p4)

```

# sumo

```{r}
# Merge clusters with metadata
df <- merge(clusters, metadata_filt, by.x='sample', by.y='row.names')
rownames(df) <- df$sample

#| fig.path: "figures/cluster_"
#| fig.width: 6
#| fig.height: 5
#| dpi: 150

ggplot(df, aes(x=factor(label), fill=factor(affected))) +
  geom_bar(position="fill") +
  labs(x="Cluster", y="Proportion", fill="Affected") +
  scale_y_continuous(labels=scales::percent_format()) +
  theme_minimal()

```

